---
- hosts: 127.0.0.1
  vars: 
    Environment : "development"
   
  tasks:
  - name: "Create and Execute plan. Skipped if bucketName is not defined"
    when: bucketName is defined
    environment:
      TF_VAR_bucketName : "{{bucketName}}"
      TF_VAR_environment : "{{Environment}}"
    terraform:
      project_path: "/home/ec2-user/environment/terraform"
      state: present

  - name: "Execute plan file. Skipped in planFile not defined"
    when: planFile is defined
    terraform:
      project_path: "/home/ec2-user/environment/terraform"
      state: planned
      plan_file: "{{planFile}}"
